US1762588 - React Native Demo Components Refactor and Props
Worldpay/access-checkout-react-native pull request #86
Opened 2024-01-09 12:44 UTC by abaeza-wp

2024-01-11 14:27 UTC, ochalet-wp requested changes

2024-01-11 14:27 UTC, ochalet-wp commented on access-checkout-react-native-sdk/src/ui/AccessCheckoutTextInput.tsx
> + *   fontWeight:applies to both placeholder text and input text.
Can we remove fontStyle and fontWeight from this cimment?

2024-01-11 14:27 UTC, ochalet-wp commented on demo-app/src/common/CvcField.tsx
> +  const validationColourStyle = props.isEditable ? validationColours : 'silver';
We might get merchants feedback that the border does not change automatically when AccessCheckoutTextInput is disabled. Let's just and see feedback then :)

2024-01-12 09:10 UTC, abaeza-wp reviewed
US1762588: Remove unnecessary comments

2024-01-12 17:20 UTC, ochalet-wp approved these changes

2024-01-15 08:20 UTC, merged